version: '3.1'
services:

  redis:
    image: 'redis:7.0'
    networks:
      - hmpps_int
    ports:
      - '6379:6379'

  wiremock:
    image: wiremock/wiremock:2.35.0 # match version in .circleci/config.yml
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"

networks:
  hmpps_int:
