main_branch: &main_branch
  filters:
    branches:
      only: main

feature_branch: &feature_branch
  filters:
    branches:
      ignore: main

version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@10
  slack: circleci/slack@4

parameters:
  alerts-slack-channel:
    type: string
    default: visits-alerts

  releases-slack-channel:
    type: string
    default: visits-releases

  node-version:
    type: string
    default: 22.15-browsers

jobs:
  acceptance_tests_staff_playwright-e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.51.0-jammy
    circleci_ip_ranges: true
    steps:
      - run:
          name: Checkout VSIP Staff UI Playwright E2E Tests
          command: git clone https://github.com/ministryofjustice/hmpps-book-a-prison-visit-staff-e2e-tests.git
      - run:
          name: get git status
          command: |
            cd hmpps-book-a-prison-visit-staff-e2e-tests
            git checkout main
            git pull
            git status
      - attach_workspace:
          at: ~/app
      - run:
          name: Install Dependencies
          command: |
            cd hmpps-book-a-prison-visit-staff-e2e-tests
            npm ci --no-audit
      - run:
          name: Run Playwright Tests
          command: |
            cd hmpps-book-a-prison-visit-staff-e2e-tests
            npm run test:ci
      - store_test_results:
          path: /root/project/hmpps-book-a-prison-visit-staff-e2e-tests/results.xml
      - store_artifacts:
          path: /root/project/hmpps-book-a-prison-visit-staff-e2e-tests/playwright-report/index.html
      - store_artifacts:
          path: /root/project/hmpps-book-a-prison-visit-staff-e2e-tests/test-results

  build:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          command: |
            npm run build
      - run: # Run linter after build because the integration test code depends on compiled typescript...
          name: Linter check
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - dist
            - assets/stylesheets

  unit_test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: unit tests
          command: npm run test:ci
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results/unit-test-reports.html
      - store_artifacts:
          path: test_results/jest/coverage

  integration_test:
    executor:
      name: hmpps/node_redis
      node_tag: << pipeline.parameters.node-version >>
      redis_tag: "7.0"
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Install missing OS dependency
          command: sudo apt-get install libxss1
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Get wiremock
          command: curl -o wiremock.jar https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.9.2/wiremock-standalone-3.9.2.jar
      - run:
          name: Run wiremock
          command: java -jar wiremock.jar --port 9091
          background: true
      - run:
          name: Run the node app.
          command: npm run start-feature
          background: true
      - run:
          name: Wait for node app to start
          command: sleep 5
      - run:
          name: integration tests
          command: npm run int-test
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: integration_tests/videos
      - store_artifacts:
          path: integration_tests/screenshots

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - unit_test:
          requires:
            - build
      - integration_test:
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker

      - request-dev-preview-approval:
          <<: *feature_branch
          type: approval
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker
      - hmpps/deploy_env:
          <<: *feature_branch
          name: deploy_dev_preview
          env: "dev"
          context: hmpps-common-vars
          requires:
            - request-dev-preview-approval

      - request-staging-preview-approval:
          <<: *feature_branch
          type: approval
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker
      - hmpps/deploy_env:
          <<: *feature_branch
          name: deploy_staging_preview
          env: "staging"
          context:
            - hmpps-common-vars
            - book-a-prison-visit-staff-ui-stage
          requires:
            - request-staging-preview-approval

      - request-acceptance-tests-preview-staff-playwright-approval:
          <<: *feature_branch
          type: approval
          requires:
            - deploy_staging_preview
      - acceptance_tests_staff_playwright-e2e:
          <<: *feature_branch
          requires:
            - request-acceptance-tests-preview-staff-playwright-approval
          context: playwright-book-a-prison-visit-staff-e2e-ui-tests-staging

      - request-preprod-preview-approval:
          <<: *feature_branch
          type: approval
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker
      - hmpps/deploy_env:
          <<: *feature_branch
          name: deploy_preprod_preview
          env: "preprod"
          context:
            - hmpps-common-vars
            - book-a-prison-visit-staff-ui-preprod
          requires:
            - request-preprod-preview-approval

      - hmpps/deploy_env:
          <<: *main_branch
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker

      - hmpps/deploy_env:
          <<: *main_branch
          name: deploy_staging
          env: "staging"
          context:
            - hmpps-common-vars
            - book-a-prison-visit-staff-ui-stage
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker

      - request-acceptance-tests-staff-playwright-approval:
          <<: *main_branch
          type: approval
          requires:
            - deploy_staging
      - acceptance_tests_staff_playwright-e2e:
          <<: *main_branch
          requires:
            - request-acceptance-tests-staff-playwright-approval
          context: playwright-book-a-prison-visit-staff-e2e-ui-tests-staging

      - request-preprod-approval:
          <<: *main_branch
          type: approval
          requires:
            - deploy_dev
            - deploy_staging
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - book-a-prison-visit-staff-ui-preprod
          requires:
            - request-preprod-approval

      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - book-a-prison-visit-staff-ui-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "30 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "0 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
