apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-page-staff
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  maintenance-page-staff
  template:
    metadata:
      labels:
        app: maintenance-page-staff
    spec:
      containers:
      - name: maintenance-page-staff
        image:  ministryofjustice/vsip-maintenance:0.1.1
        ports:
        - containerPort: 8080

        securityContext:
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
