---
# Per environment values which override defaults in book-a-prison-visit-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-prison-visits-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-prison-visits-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    NOMIS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    ORCHESTRATION_API_URL: "https://hmpps-manage-prison-visits-orchestration-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    PRISONER_CONTACT_REGISTRY_API_URL: "https://prisoner-contact-registry-preprod.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: https://frontend-components-preprod.hmpps.service.justice.gov.uk
    DPS_URL: "https://dps-preprod.prison.service.justice.gov.uk/"
    DPS_PRISONER_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk/"

    REDIS_KEY: "bapv-staff-preprod"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

