---
# Per environment values which override defaults in book-a-prison-visit-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-a-prison-visit-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-a-prison-visit-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

