# Per environment values which override defaults in book-a-prison-visit-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-prison-visits-staging.prison.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    INGRESS_URL: "https://manage-prison-visits-staging.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    NOMIS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ORCHESTRATION_API_URL: "https://hmpps-manage-prison-visits-orchestration-staging.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    PRISONER_CONTACT_REGISTRY_API_URL: "https://prisoner-contact-registry-staging.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-dev.service.justice.gov.uk"
    COMPONENT_API_URL: https://frontend-components-dev.hmpps.service.justice.gov.uk
    DPS_URL: "https://dps-dev.prison.service.justice.gov.uk/"
    DPS_PRISONER_URL: "https://prisoner-dev.digital.prison.service.justice.gov.uk/"
    APPLICATIONINSIGHTS_CONNECTION_STRING: null # disable App Insights for staging
    REDIS_KEY: "bapv-staff-staging"
    ENVIRONMENT_NAME: STAGING

  namespace_secrets:
    book-a-prison-visit-staff-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: null # disable App Insights for staging

  allowlist:
    groups:
      - internal
      - prisons
      - circleci

generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
  businessHoursOnly: true
