# Per environment values which override defaults in book-a-prison-visit-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-prison-visits-dev.prison.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    INGRESS_URL: "https://manage-prison-visits-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ORCHESTRATION_API_URL: "https://hmpps-manage-prison-visits-orchestration-dev.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    PRISONER_CONTACT_REGISTRY_API_URL: "https://prisoner-contact-registry-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://dps-dev.prison.service.justice.gov.uk/"
    DPS_PRISONER_URL: "https://prisoner-dev.digital.prison.service.justice.gov.uk/"
    DPS_CONTACTS_URL: "https://contacts-dev.hmpps.service.justice.gov.uk"
    DPS_INCENTIVES_URL: "https://incentives-ui-dev.hmpps.service.justice.gov.uk/"
    REDIS_KEY: "bapv-staff-dev"
    ENVIRONMENT_NAME: dev
    NODE_USE_ENV_PROXY: "1"
    APPLICATION_INSIGHTS_NO_STATSBEAT: "true"

    FEATURE_REMAND_LIMITS: "true"

  namespace_secrets:
    hmpps-envoy-https-proxy-env:
      HTTP_PROXY: "HTTP_PROXY"
      HTTPS_PROXY: "HTTPS_PROXY"
      NO_PROXY: "NO_PROXY"
      http_proxy: "HTTP_PROXY"
      https_proxy: "HTTPS_PROXY"
      no_proxy: "NO_PROXY"

  allowlist:
    groups:
      - internal
      - prisons
      - circleci

generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
  businessHoursOnly: true
