---
# Per environment values which override defaults in book-a-prison-visit-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-prison-visits-staging.prison.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    INGRESS_URL: "https://manage-prison-visits-staging.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    NOMIS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ORCHESTRATION_API_URL: "https://hmpps-manage-prison-visits-orchestration-staging.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-offender-search-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    PRISONER_CONTACT_REGISTRY_API_URL: "https://prisoner-contact-registry-staging.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-dev.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk/"
    SMS_NOTIFICATIONS_ENABLED: "true"
    REDIS_KEY: "bapv-staff-staging"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    ark-dom1-psn1: 51.247.4.0/24
    ark-dom1-psn2: 51.247.3.0/24
    ark-nps-hmcts-ttp1: 195.59.75.0/24
    ark-nps-hmcts-ttp2: 194.33.192.0/25
    ark-nps-hmcts-ttp3: 194.33.193.0/25
    ark-nps-hmcts-ttp4: 194.33.196.0/25
    ark-nps-hmcts-ttp5: 194.33.197.0/25
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    quantum1: 62.25.109.197/32
    quantum2: 212.137.36.230/32
    quantum3: 195.92.38.16/28
    moj-official-tgw-preprod: 51.149.251.0/24
    moj-official-tgw-prod: 51.149.250.0/24
    moj-official-ark-c-expo-e: 51.149.249.0/29
    moj-official-ark-c-vodafone: 194.33.248.0/29
    moj-official-ark-f-vodafone: 194.33.249.0/29
    moj-official-ark-f-expo-e: 51.149.249.32/29
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    circleci-1: "3.228.39.90"
    circleci-2: "18.213.67.41"
    circleci-3: "34.194.94.201"
    circleci-4: "34.194.144.202"
    circleci-5: "34.197.6.234"
    circleci-6: "35.169.17.173"
    circleci-7: "35.174.253.146"
    circleci-8: "52.3.128.216"
    circleci-9: "52.4.195.249"
    circleci-10: "52.5.58.121"
    circleci-11: "52.21.153.129"
    circleci-12: "52.72.72.233"
    circleci-13: "54.92.235.88"
    circleci-14: "54.161.182.76"
    circleci-15: "54.164.161.41"
    circleci-16: "54.166.105.113"
    circleci-17: "54.167.72.230"
    circleci-18: "54.172.26.132"
    circleci-19: "54.205.138.102"
    circleci-20: "54.208.72.234"
    circleci-21: "54.209.115.53"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

